// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIgEsiKW2zlANPBMbCLOdkbBfbLrrr1rc',
    appId: '1:806410887635:android:a139d72bf337d8f5100f26',
    messagingSenderId: '806410887635',
    projectId: 'czestujem',
    storageBucket: 'czestujem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP9iHt1nMRlViX7mXc34PbNuZ4rsQ0pFQ',
    appId: '1:806410887635:ios:6d6d18d700c0accb100f26',
    messagingSenderId: '806410887635',
    projectId: 'czestujem',
    storageBucket: 'czestujem.appspot.com',
    iosClientId: '806410887635-d6tsap1dqtea1rseaq7ugbqd4g7653q7.apps.googleusercontent.com',
    iosBundleId: 'com.example.czestujem',
  );
}
